### PR TITLE
Add repeating (new) game functionality

### PR DESCRIPTION
**Pull request by Z-Red**
This PR will complete half of #3. That is, the user can now specify if they would like to play another game.

What is left: the scoreboard must be shown post-game, but this is component is being blocked by the completion of #2.

### CODE REVIEW

**Review by derek-repka — CHANGES_REQUESTED** [review]
The play again functionality should probably be moved to the main function, as calling playGame() from inside playGame() is not ideal due to all the function calls returning all at once when no more games were to be played. This can be accomplished by having a while loop in the main function that will play the game, then prompt the user for if they want to play again, and reset the board state and continue the loop for as long as they want to play again.

**Comment by corey1994** [comment]
Just for correctness of the PR description: are #2 and #3 switched?  I believe that #3 requires that the user can start another game, and #2 requires the scoreboard.  Unless I'm misunderstanding your description.

**Comment by Z-Red** [comment]
> Just for correctness of the PR description: are #2 and #3 switched? I believe that #3 requires that the user can start another game, and #2 requires the scoreboard. Unless I'm misunderstanding your description.

The original comment has been edited for accuracy.

**Comment by Z-Red** [comment]
@derek-repka The change requested has been resolved: the potentially deep call stack issue is fixed by delegating continuous gameplay to the main function rather than within the playGame function. d84d1ac

**Review by derek-repka — APPROVED** [review]

**Pull request merged**
